### ISSUE TITLE
Problema leyendo el archivo adobe de la presentacion

### ISSUE THREAD

**Issue by ginerorama** [oscarperpinan/intro_github#2]
## Problema con el fichero .pdf

No consigo abrir el archivo  **intro_github.pdf**  puede ser que este corrupto?.

**Comment by oscarperpinan** [comment]
Disculpas por la tardanza en responder. No había recibido ninguna notificación sobre esta issue.
He comprobado el fichero y es correcto. Se puede abrir tanto en el visor de github como en descarga directa.
